#-*- coding:utf-8 -*-
"""
Django settings for mySjjg project.

Generated by 'django-admin startproject' using Django 1.8.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'ab6b&(#pcl52ln4)+x56_a3v^n-q3!lrq*as(pi&8ynv3+*47g'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


ALLOWED_HOSTS = ['127.0.0.1', 'localhost']


# Application definition

INSTALLED_APPS = (
    'ckeditor',
    'suit',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'sjjgWeb',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',

)

ROOT_URLCONF = 'mySjjg.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.core.context_processors.request',
            ],
        },
    },
]
"""from django.conf.global_settings import TEMPLATE_CONTEXT_PROCESSORS as TCP

TEMPLATE_CONTEXT_PROCESSORS = TCP + (

)"""

#If you deploy your project with Apache or Debug=False don’t forget to run ./manage.py collectstatic

WSGI_APPLICATION = 'mySjjg.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases
import socket

if socket.gethostname() == 'DXQCLAAB6GLF1XR':
    DEBUG = True
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'sjjgdb',
            'USER':'root',
            'PASSWORD':''
        }
    }
else:
    DEBUG = True
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'sjjgdb',
            'USER':'root',
            'PASSWORD':'root'
        }
    }


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/
AUTH_USER_MODEL = 'sjjgWeb.User'   #默认user

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/
SITE_URL = 'Http://127.0.0.1:8000'

STATIC_URL = '/static/'

STATICFILES_DIRS = (
    os.path.join(BASE_DIR,'static'),
)

#文本编辑器路径配置
MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR,"midea")

print MEDIA_ROOT
CKEDITOR_UPLOAD_PATH = "article_images"  #这是个相对路径，相对应MEDIA_ROOT

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Full',
        'height': 300,
        'width':715,
    },
}


#suit config
SUIT_CONFIG = {
    'ADMIN_NAME':'数据结构后台管理',        #后台的name
    'MENU_EXCLUDE':('auth.group','auth'), #排除app和model
    'CONFIRM_UNSAVED_CHANGES': True,
    'MENU_OPEN_FIRST_CHILE': False,
    'MENU_ICONS':{
        'site':'icon-lock',
        'auth':'icon-lock',
    },
    'MENU_ORDER': (
      # To add custom item, define it as tuple or list:
      # For parent: (Name, Link, Icon, Permission) - Last two are optional
      # For child: (Name, Link, Permission) - Last one is optional
      # You can also mix custom and native apps and models
      # Link can be absolute url or url name
      # Permission can be string or tuple/list for multiple
      # If MENU_OPEN_FIRST_CHILD=True and children exists, you can leave parent link blank

      # Example:

      (
        ('课程信息', '/admin/sjjgWeb/information', 'icon-cog', ('auth.add_group',)),
            (
                ('课程介绍', '/admin/sjjgWeb/information/1/',),
                ('课程大纲', '/admin/sjjgWeb/information/2/'),
                ('课程实验','/admin/sjjgWeb/publishinformation/8/',('sjjgweb.add_publishInformation')),
                ('课程设计大纲','/admin/sjjgWeb/information/4/'),
            )
      ),
      (
            ('教学团队','/admin/sjjgWeb/information/3/','icon-cog',),
            (
                ('课程负责人' ,'/admin/sjjgWeb/information/3/'),
                ('教学团队','/admin/sjjgWeb/publishinformation/15/'),
            )
      ),
        (
            ('教学资源','/admin/sjjgWeb/information/3/','icon-cog',),
            (
                ('教学录像','/admin/sjjgWeb/publishfile/1/'),
                ('授课教案','/admin/sjjgWeb/publishfile/2/'),
                ('课外作业','/admin/sjjgWeb/publishinformation/9/'),
            ),
        ),
        (
            ('扩展资源','/admin/sjjgWeb/information/3/','icon-cog',),
            (
                ('案例库','/admin/sjjgWeb/publishinformation/10/'),
                ('专题讲座','/admin/sjjgWeb/publishinformation/11/'),
                ('资源教材','/admin/sjjgWeb/publishinformation/12/'),
            ),

        ),
        (
            ('资讯中心','/admin/sjjgWeb/information/3/','icon-cog',),
            (
                ('课程公告','/admin/sjjgWeb/coursepublish/1/'),
                ('课外活动','/admin/sjjgWeb/coursepublish/4/'),
            ),
        ),
        (
            ('教研成果','/admin/sjjgWeb/information/3/','icon-cog',),
            (
                ('教研成果','/admin/sjjgWeb/coursepublish/2/'),
                ('教研教改','/admin/sjjgWeb/publishinformation/14/'),
            ),
        ),

        #user管理
        (
            ('学生管理','/admin/sjjgWeb/student/','icon-user',),
        ),
        #在线测试试卷
        (
            ('在线测试试卷管理','/admin/sjjgWeb/tests/','icon-leaf',),
        ),
        #留言管理
        (
            ('互动平台留言管理','/admin/sjjgWeb/comment/','icon-earth'),
        ),
     ),

    'SEARCH_URL': '/admin/sjjgWeb/student/',
    'LIST_PER_PAGE':20,
}



